In [1]:
import sys
import cv2
import numpy as np
# np.set_printoptions(threshold=sys.maxsize)

In [6]:
filename = 'images/img1.png'
img = cv2.imread(filename)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gray

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [240, 240, 240, ...,   0,   0,   0],
       [240, 240, 240, ...,   0,   0,   0],
       [240, 240, 240, ...,   0,   0,   0]], dtype=uint8)

In [8]:
gray = np.float32(gray)
gray

array([[  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       ...,
       [240., 240., 240., ...,   0.,   0.,   0.],
       [240., 240., 240., ...,   0.,   0.,   0.],
       [240., 240., 240., ...,   0.,   0.,   0.]], dtype=float32)

In [10]:
dst = cv2.cornerHarris(gray,2,3,0.04)
dst

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [11]:
dst = cv2.dilate(dst,None)
dst

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [13]:
img[dst>0.01*dst.max()]=[0,0,255]
cv2.imshow('dst',img)
if cv2.waitKey(0) & 0xff == 27:
    cv2.destroyAllWindows()